image: Visual Studio 2019
platform: 
    - x64
environment:
    matrix:
    - PYTHON: "C:\\Python313-x64"
install :
   - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel Cython numpy"
   - "%PYTHON%\\python.exe -m pip install pandas"
   - "%PYTHON%\\python.exe -m pip install pyinstaller pillow flet"
   - "%PYTHON%\\python.exe - m pip install -r requirements.txt"
build_script: 
    - flet pack ./src/main.py	--n "Simple Gym" -i ./assets/icon.jpg --product-name "Simple Gym" --product-version "1.0.0" --file-description "A Simple gym management app"
artifacts: 
   - path: dist\*

test: off
